[2024-05-13 00:29:50,166] ERROR exception() L268  Exception in worker process - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L268 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/wsgi.py", line 7, in <module>
    application = create_app()
                  ^^^^^^^^^^^^
  File "/app/app.py", line 12, in create_app
    produtos.register_endpoint.configure(app)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'function' object has no attribute 'configure'
[2024-05-13 00:29:50,168] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-13 00:32:26,196] ERROR exception() L268  Exception in worker process - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L268 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/wsgi.py", line 7, in <module>
    application = create_app()
                  ^^^^^^^^^^^^
  File "/app/app.py", line 12, in create_app
    app.register(produtos)
    ^^^^^^^^^^^^
AttributeError: 'OpenAPI' object has no attribute 'register'
[2024-05-13 00:32:26,197] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-13 00:34:48,934] ERROR exception() L268  Exception in worker process - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L268 
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 583, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 119, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 144, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 49, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 39, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 358, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/app/wsgi.py", line 7, in <module>
    application = create_app()
                  ^^^^^^^^^^^^
  File "/app/app.py", line 12, in create_app
    app.configure(produtos)
    ^^^^^^^^^^^^^
AttributeError: 'OpenAPI' object has no attribute 'configure'
[2024-05-13 00:34:48,935] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-13 00:51:03,361] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-13 00:53:21,360] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-13 01:03:55,305] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 19:39:57,901] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 19:47:35,213] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 19:50:19,798] INFO info() L262  Worker exiting (pid: 6) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 19:51:24,321] INFO info() L262  Worker exiting (pid: 8) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 20:15:47,422] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 20:17:43,120] INFO info() L262  Worker exiting (pid: 8) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 20:19:38,063] INFO info() L262  Worker exiting (pid: 6) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 20:20:12,972] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 20:25:03,295] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-16 20:27:01,785] INFO info() L262  Worker exiting (pid: 8) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-17 19:33:29,457] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-17 19:33:29,469] INFO info() L262  Worker exiting (pid: 8) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-17 20:16:59,143] INFO info() L262  Worker exiting (pid: 8) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
[2024-05-17 20:16:59,232] INFO info() L262  Worker exiting (pid: 7) - call_trace=/usr/local/lib/python3.11/site-packages/gunicorn/glogging.py L262 
